'''
Each new term in the Fibonacci sequence is generated by adding the previous two 
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
'''
total = 2

def next_fib(a, b):
    '''function to return the next number in the Fibonacci sequence'''
    result = a + b
    return result


def add_even_fibs(a, b, limit):
    '''function to return th sum of even numbe in the Fibonacci sequence
    up to a specified value'''
    
    global total
    
    # Get the next Fibonacci number
    result = next_fib(a, b)
    
    # Add the result to the total if the result is even
    if result % 2 == 0 and result <= limit:
        total += result
        # Get the next value in the sequence
    
    if result <= limit:
        add_even_fibs(b, result, limit)
    
    # Return the total to the program
    return total

print(add_even_fibs(1, 2, 4000000))